
import { AeroGearConfiguration, INSTANCE, ServiceConfiguration } from "@aerogear/core";

/**
 * Initialize all platform SDK's by using configuration generated by AeroGear command line client
 *
 * @param config object containing SDK. Object can be read from file or pasted directly in source code.
 */
export const init = (config: AeroGearConfiguration): void => {
  return INSTANCE.init(config);
};

/**
 * Get a custom runtime connector configuration
 *
 * @param id - id of the custom runtime connector
 */
export const getCustomRuntimeConfigById = (id: string): ServiceConfiguration | undefined => {
  return INSTANCE.getConfigById(id);
};
