= AeroGear Services Core SDK

The Core SDK provides helpers for parsing the configuration file and share common utilities between other SDK modules.

It's main features are:

* Parsing of the configuration file
* Logging
* Metrics gathering

== Installation

The `@aerogear/core` module is available via NPM:

----
npm install @aerogear/core
----

=== Additional steps for a Cordova project

After node module installation via NPM use the Cordova CLI to add the additional native dependencies to your project:

----
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-app-version
----

This will install the packages with these native dependencies from the NPM registry and properly link all native dependencies to the project's cordova Platforms.

Refer to the link:./getting-started[Getting Started] guide for more information on installing the AeroGear SDK.

== Usage

The Core module supports parsing of the configuration file generated by the mobile CLI:

[source, javascript]
----
import {MobileCore, MetricsService} from '@aerogear/core';
import configuration from '../mobile-services.json';

const parser = new ConfigurationHelper(appConfig);
const metricsConfig = parser.getConfig(MetricsService.ID);
----

=== Metrics Service

Metrics is another service provided by Core and no further dependencies are required for its utilization.
It provides registration of default metrics for the application such as App and Device information as well as supplying these services to other modules of the SDK.

[source, javascript]
----
import { MetricsService } from '@aerogear/core';
import configuration from '../mobile-services.json';
const metrics = new MetricsService(configuration);
metrics.sendAppAndDeviceMetrics().then(() => {
  console.info("Metrics registered successfully");
});
----

App metrics record:

- *ID*: The identifier of your App
- *App version*: The version of your App
- *SDK version*: The version of the Aerogear JS SDK that is used

=== Device metrics

- *Platform*: The `cordova-` prefix along with the native platform being run on
- *Platform Version*: The runtime version of your chosen platform
