= AeroGear Services Metrics SDK

Metrics is another service provided by Core and no further dependencies are required for its utilization.
It provides registration of default metrics for the application such as App and Device information as well as supplying these services to other modules of the SDK.

== Usage
With an instance of the `MetricsService` class, it is possible to send default (app and device) as well as custom metrics to an https://github.com/aerogear/aerogear-app-metrics[Aerogear App Metrics] instance.

[source, javascript]
----
import { Metrics, MetricsService } from '@aerogear/core';
import configuration from '../mobile-services.json';

// Instance of MetricsService
const metrics = new MetricsService(configuration);

// Sending default metrics
metrics.sendAppAndDeviceMetrics()
  .then(() => {
    console.info("Metrics registered successfully");
  });

// Sending additional custom metrics
const customMetrics: Metrics[] = gatherCustomMetrics();
metrics.publish("my-custom-type", customMetrics)
  .then(() => {
    console.info("Custom metrics registered successfully");
  });
----

== Default metrics

The default metrics are always sent alongside any custom metrics. They are composed by the following fields:

App metrics::
- *App version*: The version of your App
- *SDK version*: The version of the Aerogear JS SDK that is used

Device metrics::
- *Platform*: The `cordova-` prefix along with the native platform being run on
- *Platform Version*: The runtime version of your chosen platform