== AeroGear Services JavaScript Metrics SDK

=== Prerequisites

* The main SDK, see xref:getting-started.adoc[Getting Started]

==== Metrics native plugins
Install the 
[source, bash]
cordova plugin add @aerogear/cordova-plugin-aerogear-metrics

=== Deploy Metrics in Openshift

Deploy an instance of the Metrics Service from the Openshift console.

=== Provided Metrics

The default metrics contain app and device metrics and possibly other types will be added in the future.

A client id and a timestamp are added to the top level of the metrics object for categorization and visualization purposes.
The client id will be generated and stored on the device when the app is started the first time.

App Metrics::
* *App ID*: The package name of your App
* *App version*: The version of your App as defined in the top level `build.gradle`
* *SDK version*: The version of the Aerogear SDK that is used
* *Framework*: Framework used for development ("cordova" in this case)

Device Metrics::
* *Platform*: Hardcoded to `cordova`
* *Platform Version*: The API level of the device
