= AeroGear Services Metrics SDK

This document explains how to use and integrate the AeroGear Metrics SDK on a Cordova application.

=== Install Dependencies

Install the necessary dependencies in the app by running the following commands in your terminal:

[source.bash]
npm install @aerogear/app @aerogear/core
cordova plugin add @aerogear/cordova-plugin-aerogear-metrics

=== Deploy Metrics in Openshift

Deploy an instance of Metrics from the Openshift console.

=== Get the App Configuration

The configuration needed to initialize the AeroGear SDK is contained in a JSON file generated by the https://github.com/aerogear/mobile-cli[AeroGear Mobile CLI]. It has the necessary parameters for every deployed service as well as other global ones. It should look like:

```
{
  "version": 1,
  "clusterName": "192.168.64.74:8443",
  "namespace": "my-project",
  "clientId": "my-app-id",
  "services": [
    {
      "id": "metrics",
      "url": "http://...",
      ...
    },
    ...
  ]
}
```

=== Usage

After dependencies are installed, call `init` from `@aerogear/app` when the app just starts:

```
import { init } from "@aerogear/app";

const appConfig = { ... };

document.addEventListener("deviceready", () => init(appConfig), false);
```

As part of the SDK initialization, the relevant app and device data will be sent to the server automatically. Metrics is designed to send the data only on app startup, hence it shouldn't (and can't) be used manually.

=== Provided Metrics

The default metrics contain app and device metrics and possibly other types will be added in the future.

A client id and a timestamp are added to the top level of the metrics object for categorization and visualization purposes.
The client id will be generated and stored on the device when the app is started the first time.

==== App Metrics

 *App ID*: The package name of your App
 *App version*: The version of your App as defined in the top level `build.gradle`
 *SDK version*: The version of the Aerogear SDK that is used
 *Framework*: Framework used for development ("cordova" in this case)

===== Device Metrics

 *Platform*: Hardcoded to `android`
 *Platform Version*: The API level of the device
